[[permission]]
identifier = "allow-chrome-analyze"
description = "Failed in working."
commands.allow = [
  "chrome_list_profiles",
  "chrome_analyze_passwords",
  "chrome_analyze_cookies",
  "chrome_analyze_sessions",
  "chrome_analyze_stored_data",
]
