import { clearSession, getClinic, getToken } from '@/lib/session'
import type { AuthCredentials, AuthResult, AuthStatusResponse } from '@/types/auth'
import type { PatientRow } from '@/types/patient'

const MOCK_CODE = 'roswell123'

export const mockAuth = {
  async authenticate(credentials: AuthCredentials): Promise<AuthResult> {
    await delay(600)

    if (credentials.code.trim().toLowerCase() === MOCK_CODE) {
      return {
        ok: true,
        clinic: {
          id: 'CLN-101',
          name: 'Roswell Primary Care',
        },
        token: 'mock-jwt-token',
        message: 'Success!',
      }
    }

    return { ok: false, message: 'Clinic not found' }
  },

  async checkStatus(): Promise<AuthStatusResponse> {
    await delay(300)
    const token = getToken()
    const clinic = getClinic()

    if (token && clinic != null) {
      return { authenticated: true, clinic }
    }

    return { authenticated: false }
  },

  async logout(): Promise<void> {
    clearSession()
  },
}

export const mockInsurance = [
  { ins_id: 'INS-AET', ins_name: 'Aetna' },
  { ins_id: 'INS-UHC', ins_name: 'UnitedHealthcare' },
]

export const mockPcpList = [
  { pcp_id: '1', pcp_name: 'John Smith' },
  { pcp_id: '2', pcp_name: 'Sarah Lee' },
]

export const mockQualityPrograms: Record<
  string,
  { qp_id: string; qp_name: string }[]
> = {
  '0': [
    { qp_id: 'QP-01', qp_name: 'Quality Program Alpha' },
    { qp_id: 'QP-02', qp_name: 'Quality Program Beta' },
  ],
  'INS-AET': [{ qp_id: 'QP-01', qp_name: 'Quality Program Alpha' }],
  'INS-UHC': [{ qp_id: 'QP-02', qp_name: 'Quality Program Beta' }],
}

export const mockStatusColors = [
  {
    id: 1,
    status_type: 'measure',
    measure_status_display: 'Open',
    status_category_display: 'Open',
    status_description: 'Measure is open and awaiting completion.',
    text_color: '#1d4ed8',
    bg_color: '#dbeafe',
  },
  {
    id: 5,
    status_type: 'measure',
    measure_status_display: 'Measure Alert',
    status_category_display: 'Alert',
    status_description: 'Measure requires immediate review or action.',
    text_color: '#9a3412',
    bg_color: '#ffedd5',
  },
  {
    id: 18,
    status_type: 'measure',
    measure_status_display: 'Measure Critical',
    status_category_display: 'Critical',
    status_description: 'Critical measure status that needs urgent attention.',
    text_color: '#ffffff',
    bg_color: '#dc2626',
  },
  {
    id: 4,
    status_type: 'measure',
    measure_status_display: 'Compliant',
    status_category_display: 'Compliant',
    status_description: 'Measure is completed with date of service and a value.',
    text_color: '#1d4ed8',
    bg_color: '#eef2ff',
  },
  {
    id: 2,
    status_type: 'measure',
    measure_status_display: 'Closed',
    status_category_display: 'Closed',
    status_description: 'Measure has been closed and no further action is required.',
    text_color: '#166534',
    bg_color: '#dcfce7',
  },
  {
    id: 3,
    status_type: 'patient',
    measure_status_display: 'Pending',
    status_category_display: 'Pending',
    status_description: 'Patient status is pending review or follow-up.',
    text_color: '#b45309',
    bg_color: '#fef3c7',
  },
  {
    id: 6,
    status_type: 'patient',
    measure_status_display: 'Patient Hold',
    status_category_display: 'Hold',
    status_description: 'Patient record is on hold and should not be closed yet.',
    text_color: '#7c2d12',
    bg_color: '#fed7aa',
  },
  {
    id: 8,
    status_type: 'patient',
    measure_status_display: 'Patient Review',
    status_category_display: 'Review',
    status_description: 'Patient case is under active review by the care team.',
    text_color: '#92400e',
    bg_color: '#fef3c7',
  },
  {
    id: 13,
    status_type: 'patient',
    measure_status_display: 'Patient Action',
    status_category_display: 'Action',
    status_description: 'Patient action is required to move the measure forward.',
    text_color: '#b45309',
    bg_color: '#fde68a',
  },
  {
    id: 28,
    status_type: 'patient',
    measure_status_display: 'Patient Critical',
    status_category_display: 'Critical',
    status_description: 'Patient status is critical and needs immediate intervention.',
    text_color: '#ffffff',
    bg_color: '#b91c1c',
  },
  {
    id: 10,
    status_type: 'eligibility',
    measure_status_display: 'Eligible',
    status_category_display: 'Eligible',
    status_description: 'Patient meets eligibility criteria for this measure.',
    text_color: '#047857',
    bg_color: '#d1fae5',
  },
  {
    id: 11,
    status_type: 'eligibility',
    measure_status_display: 'Not Eligible',
    status_category_display: 'Not Eligible',
    status_description: 'Patient does not meet eligibility criteria for this measure.',
    text_color: '#b91c1c',
    bg_color: '#fee2e2',
  },
  {
    id: 12,
    status_type: 'eligibility',
    measure_status_display: 'Pending Eligibility',
    status_category_display: 'Pending',
    status_description: 'Eligibility has not been confirmed yet.',
    text_color: '#b45309',
    bg_color: '#fef3c7',
  },
  {
    id: 20,
    status_type: 'measure_report',
    measure_status_display: 'Reported',
    status_category_display: 'Reported',
    status_description: 'Measure has been reported successfully.',
    text_color: '#1d4ed8',
    bg_color: '#dbeafe',
  },
  {
    id: 21,
    status_type: 'measure_report',
    measure_status_display: 'Not Reported',
    status_category_display: 'Not Reported',
    status_description: 'Measure has not been reported yet.',
    text_color: '#9a3412',
    bg_color: '#ffedd5',
  },
  {
    id: 22,
    status_type: 'measure_report',
    measure_status_display: 'Report Excluded',
    status_category_display: 'Excluded',
    status_description: 'Measure was excluded from the quality report.',
    text_color: '#64748b',
    bg_color: '#f1f5f9',
  },
]

export const mockPatients: PatientRow[] = [
  {
    source: 'hedis',
    cyear: 2026,
    ins_id: 'INS-AET',
    ins_name: 'Aetna',
    qp_id: 'QP-01',
    qp_name: 'Quality Program Alpha',
    measure_id: 'M-HBA1C',
    obs_id: 'OBS-H-001',
    measure: 'HbA1c Control',
    pt_fname: 'Maria',
    pt_lname: 'Gonzalez',
    pt_dob: '1985-03-14',
    pt_gender: 'F',
    pt_emr_id: 'EMR-78421',
    pt_subno: 'SUB-99201',
    pt_lang: 'English',
    pt_phone: '(555) 201-3344',
    pt_other_phone: '',
    pt_email: 'maria.g@email.com',
    dos: '2026-05-12',
    pcp_fname: 'John',
    pcp_lname: 'Smith',
    details: {
      value1: '7.2',
      value2: '6.8',
      appt_date: '2026-05-12',
      appt_pcp: 'Dr. Smith',
      v_status: '1',
      v_specialty: 'Endocrinology',
      m_status: '1',
      p_status: '3',
      e_status: '',
      r_status: '',
      admit_date: '',
      event_date: '2026-05-12',
      discharge_date: '',
      loinc1: '4548-4',
      loinc2: '',
      cpt1: '83036',
      cpt2: '',
      num_flag: 'Y',
      den_flag: 'Y',
    },
  },
  {
    source: 'med_adh',
    cyear: 2026,
    ins_id: 'INS-AET',
    ins_name: 'Aetna',
    qp_id: 'QP-01',
    qp_name: 'Quality Program Alpha',
    measure_id: 'M-PDC',
    obs_id: 'OBS-M-001',
    measure: 'Medication Adherence',
    pt_fname: 'Maria',
    pt_lname: 'Gonzalez',
    pt_dob: '1985-03-14',
    pt_gender: 'F',
    pt_emr_id: 'EMR-78421',
    pt_subno: 'SUB-99201',
    pt_lang: 'English',
    pt_phone: '(555) 201-3344',
    pt_other_phone: '',
    pt_email: 'maria.g@email.com',
    dos: '2026-01-15',
    pcp_fname: 'John',
    pcp_lname: 'Smith',
    details: {
      med_1: 'Metformin 500mg',
      med_2: '',
      med_3: '',
      days_adherent: 292,
      num_hit: 3,
      pdc_compliant: 'Yes',
      ability_compliant: 'Yes',
      total_days: 365,
      min_days_80_pct: 292,
      med1_pham: 'CVS Pharmacy #4521',
      med1_pham_phone: '(555) 800-1234',
      med1_pham_delivers: 'Yes',
      med1_dos: '2026-01-15',
      med1_days_supply: 90,
      med1_drug_quantity: 180,
      med1_refills_remain: 2,
      med1_refill_date: '2026-03-15',
      refill_due: '2026-03-15',
      coverage_ends: '2026-04-14',
      ndc_1: '00093-7214-01',
      risk_level: 'Low',
      appt_date: '2026-05-12',
      appt_visit: 'Follow-up',
      event_date: '2026-01-15',
      v_status: '1',
      v_specialty: 'Primary Care',
      m_status: '1',
      p_status: '4',
      e_status: '',
      r_status: '',
      rx_name: 'Metformin',
      rx_cui: '6809',
      rx_med_statue: 'Active',
      rx_dose_unit: 'mg',
      rx_dose_value: '500',
      rx_route: 'PO',
      rx_frequency: 'BID',
      rx_dispense: 'Tablet',
      rx_dates_given: '2026-01-15',
      rx_refills: '2',
      rx_dosage: '500mg BID',
      num_flag: 'Y',
      den_flag: 'Y',
    },
  },
  {
    source: 'hedis',
    cyear: 2026,
    ins_id: 'INS-UHC',
    ins_name: 'UnitedHealthcare',
    qp_id: 'QP-02',
    qp_name: 'Quality Program Beta',
    measure_id: 'M-BP',
    obs_id: 'OBS-H-002',
    measure: 'Blood Pressure Control',
    pt_fname: 'James',
    pt_lname: 'Thompson',
    pt_dob: '1972-11-08',
    pt_gender: 'M',
    pt_emr_id: 'EMR-55102',
    pt_subno: 'SUB-44102',
    pt_lang: 'English',
    pt_phone: '(555) 402-8877',
    pt_other_phone: '',
    pt_email: 'j.thompson@email.com',
    dos: '2026-04-28',
    pcp_fname: 'Sarah',
    pcp_lname: 'Lee',
    details: {
      value1: '128/82',
      value2: '124/80',
      appt_date: '2026-04-28',
      appt_pcp: 'Dr. Lee',
      v_status: '2',
      v_specialty: 'Cardiology',
      m_status: '2',
      p_status: '4',
      e_status: '',
      r_status: '',
      admit_date: '',
      event_date: '2026-04-28',
      discharge_date: '',
      loinc1: '8480-6',
      loinc2: '8462-4',
      cpt1: '99214',
      cpt2: '',
      num_flag: 'Y',
      den_flag: 'Y',
    },
  },
  {
    source: 'med_adh',
    cyear: 2026,
    ins_id: 'INS-UHC',
    ins_name: 'UnitedHealthcare',
    qp_id: 'QP-02',
    qp_name: 'Quality Program Beta',
    measure_id: 'M-PDC',
    obs_id: 'OBS-M-002',
    measure: 'Medication Adherence',
    pt_fname: 'James',
    pt_lname: 'Thompson',
    pt_dob: '1972-11-08',
    pt_gender: 'M',
    pt_emr_id: 'EMR-55102',
    pt_subno: 'SUB-44102',
    pt_lang: 'English',
    pt_phone: '(555) 402-8877',
    pt_other_phone: '',
    pt_email: 'j.thompson@email.com',
    dos: '2025-12-01',
    pcp_fname: 'Sarah',
    pcp_lname: 'Lee',
    details: {
      med_1: 'Lisinopril 10mg',
      med_2: '',
      med_3: '',
      days_adherent: 245,
      num_hit: 1,
      pdc_compliant: 'No',
      ability_compliant: 'Yes',
      total_days: 365,
      min_days_80_pct: 292,
      med1_pham: 'Walgreens #882',
      med1_pham_phone: '(555) 900-4422',
      med1_pham_delivers: 'No',
      med1_dos: '2025-12-01',
      med1_days_supply: 30,
      med1_drug_quantity: 30,
      med1_refills_remain: 5,
      med1_refill_date: '2026-04-01',
      refill_due: '2026-04-01',
      coverage_ends: '2026-04-30',
      ndc_1: '00378-1805-01',
      risk_level: 'Medium',
      appt_date: '2026-04-28',
      appt_visit: 'Annual',
      event_date: '2025-12-01',
      v_status: '2',
      v_specialty: 'Cardiology',
      m_status: '1',
      p_status: '28',
      e_status: '',
      r_status: '',
      rx_name: 'Lisinopril',
      rx_cui: '29046',
      rx_med_statue: 'Active',
      rx_dose_unit: 'mg',
      rx_dose_value: '10',
      rx_route: 'PO',
      rx_frequency: 'QD',
      rx_dispense: 'Tablet',
      rx_dates_given: '2025-12-01',
      rx_refills: '5',
      rx_dosage: '10mg QD',
      num_flag: 'Y',
      den_flag: 'Y',
    },
  },
]

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
